### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/tmp/python-typing-extensions-20230215-6738-uifapf/typing_extensions-4.5.0/dist/typing_extensions-4.5.0-py3-none-any.whl'

### ISSUE THREAD

**Issue by ivan-vilches** [jsonsmth/GPT-chatwithpdf#2]
hello what is this and how i can fix? thanks you
% pip install -r requirements.txt 
Processing /private/tmp/python-typing-extensions-20230215-6738-uifapf/typing_extensions-4.5.0/dist/typing_extensions-4.5.0-py3-none-any.whl (from -r requirements.txt (line 66))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/tmp/python-typing-extensions-20230215-6738-uifapf/typing_extensions-4.5.0/dist/typing_extensions-4.5.0-py3-none-any.whl'

**Comment by jsonsmth** [comment]
Thanks for catching that. I updated the requirements.txt here: https://github.com/jsonsmth/GPT-chatwithpdf/commit/55c13681354d9f4f43ea96281ed6995251076734

Please try again.
